version: "3.8"
services:
    coursework-db:
        image: postgres:17.5
        environment:
            POSTGRES_PASSWORD: ${DB_SUPERUSER_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - ./db:/mnt/db
            - ./db/migration:/docker-entrypoint-initdb.d
